## JavaScript에서 기본적인 에러 종류

- **ReferenceError(참조 에러)**

  존재하지 않는 변수나 함수를 사용하려고 할 때 발생합니다.

  예를 들어, 변수나 함수 이름을 잘못 입력한 경우에 발생합니다.

- **TypeError(자료형 에러)**

  잘못된 자료형을 다루려고 할 때 발생합니다.

  예를 들어, 숫자와 문자열을 더하려고 할 때 발생합니다.

- **SyntaxError(구문 에러)**

  코드가 잘못된 문법을 가지고 있을 때 발생합니다.

  예를 들어, 오타나 잘못된 키워드를 사용한 경우에 발생합니다

- **예외처리(Exception)**

  실행이 발생한 코드에서 나타나는 에러를 말한다.

## error 객체

- `error 객체`는 `new` 키워드를 사용하며, `name`, `message` 프로퍼티를 가지고 있다.

- **`throw` 객체**: 의의도적으로 에러를 발생시킬 때 사용합니다.

  예외적인 상황을 처리하거나 특정 조건에 따라 프로그램의 흐름을 제어할 때 사용됩니다.

```javascript
const error = new TypeError("에러발생");
console.log(error.name); //typeError
console.log(error.message); //에러발생
throw error; // 의도적으로 error 발생 시킨다.
```

## try catch문

- 에러가 발생하면 코드가 중지되지만 `try catch문`을 사용하면
  중지 되지않고 예외 상황을 처리할 수 있습니다.

- 실행이 가능하지 않는 에러(ex: SyntaxError)는 `try-catch 문`으로 처리하지 않고 코드를 수정하여 문제를 해결해야 합니다.

- `try` `catch` 각자 블록 스코프를 가지므로 `{}` 내부의 변수를 공유하지 않는다.

### `try catch문` 실행 과정

- **`try` 문**

  - `try` 블록 내에서 코드를 실행하고, 만약 에러가 발생하면 `catch` 블록으로 제어가 전달됩니다.

- **`catch` 문**

  - `try`에서 에러가 발생하면 `catch` 안의 코드가 실행된다.

  - `catch` 첫번째 파라미터로 `try` 안에서 발생한 에러 넘어가 다룰수 있다.

  - **catch 첫번째 파라미터**: try 안에서 발생한 에러 객체

- **`finally` 문**

  - `try-catch 문`의 마지막에 위치하며, 예외 발생 여부와 상관없이 항상 실행되는 코드 블록입니다.

  - 주로 리소스 해제 등의 정리 작업에 사용됩니다.

```javascript
try {
  const number = 10;
  console.log(number);
  number = 20; // const로 선언된 변수에 다른 값을 할당하려는 시도
  console.log(number); // 이 코드는 실행되지 않음
} catch (error) {
  console.error("에러가 발생했습니다:", error.name, error.message); // 코드 실행 된다
} finally {
  console.log("에러를 해결해주세요"); // 코드 실행 된다
}
```

### try catch 문 활용하기

- catch 블록에서 예외 객체를 캐치하여 오류에 대한 자세한 정보를 얻을 수 있습니다.

- try-catch 문을 사용하면 오류가 발생한 후에도 프로그램이 계속 실행될 수 있습니다.

```javascript
function print(nums) {
  try {
    for (const num of nums) {
      console.log(num);
    }
  } catch (err) {
    console.error(err.name);
  }
}

const number = [1, 2, 3];
print(number);
const number_name = {
  one: "상민",
  two: "종민",
  three: "호건",
}; // 에러가 발생하나 코드를 멈추지 않고 catch문으로 넘어가서 진행
print(number_name);
const numberE = ["one", "two", "three"];
print(numberE); // 정상 작동
```
